# makefile for impl
G=-g
TARGET = vsn_impl.so
OBJS = vsnIsosurf.o \

VFR_LIBDIR = ../../vfr/lib

CXX=g++
CXXFLAGS=$(G) -fPIC -I$(VFR_LIBDIR)

LINK=$(CXX)
LDFLAGS=-L$(VFR_LIBDIR) -Wl,-rpath,'$$ORIGIN'/$(VFR_LIBDIR) -shared -fPIC $(G)
LDLIBS=-lvfr_impl -lGL -lGLU

RM = rm -f
CP = cp

all: $(TARGET)

$(TARGET) : $(OBJS)
	$(CXX) -o $@ $(OBJS) $(LDFLAGS) $(LDLIBS)
	$(RM) lib$(TARGET)
	$(CP) $(TARGET) lib$(TARGET)

clean:
	$(RM) $(OBJS)

distclean: clean
	$(RM) $(TARGET) lib$(TARGET)

